ForceSensitiveOnJoin: false
DebugMessages: false
Power:
  Push:
    enabled: true
    rank: 1
    alignment: neutral
    delay: 0
  Pull:
    enabled: true
    rank: 1
    alignment: neutral
    delay: 0
  Choke:
    enabled: true
    rank: 1
    alignment: dark
    delay: 0
  Lift:
    enabled: true
    rank: 1
    alignment: light
    delay: 0
  Run:
    enabled: true
    rank: 1
    alignment: neutral
    delay: 0
  Jump:
    enabled: true
    rank: 1
    alignment: neutral
    delay: 0
  Lightning:
    enabled: true
    rank: 1
    alignment: dark
    delay: 0
  Shield:
    enabled: true
    rank: 1
    alignment: light
    delay: 0
  Flash:
    enabled: true
    rank: 1
    alignment: neutral
    delay: 0
  Heal:
    enabled: true
    rank: 1
    alignment: neutral
    delay: 0
  Rage:
    enabled: true
    rank: 1
    alignment: dark
    delay: 0
  Mediation:
    enabled: true
    rank: 1
    alignment: light
    delay: 0