name: TheLivingForce
main: de.Lathanael.TheLivingForce.bukkit.ForcePlugin
version: ${project.version} (BUILD ${git.build.time})
author: Lathanael
depend: [Spout]
description: >
             A plugin to implement the "Force" in Minecraft!

commands:
    tlf_force:
        description: Basic plugin Info
        aliases: [force]
        usage: /<command>
    tlf_info:
        description: Creates an info output to see if the system is working
        aliases: [debug]
        usage: /<command>

permissions:
    force.user:
        description: Grants access to all user related commands.
        default: true
        children:
            force.pull: true
            force.push: true
    force.admin:
        description: Grants access to all commands.
        default: op
        children:
            force.info: true
    force.info:
        description: Allows usage of the /debug command.
        default: false
    force.pull:
        description: Allows usage of the Pull force.
        default: false