name: TheLivingForce
main: de.Lathanael.ForceCraft.bukkit.ForcePlugin
version: ${project.version} (BUILD ${git.build.time})
author: Lathanael
depend: [Spout]
description: >
             A plugin to implement the "Force" in Minecraft!

commands:
    fc_force:
        description: Basic plugin Info
        aliases: [force]
        usage: /<command>
    fc_info:
        description: Gives info about the wanted player.
        aliases: [finfo]
        usage: /<command> [player]
    fc_set:
        description: Sets different properties for a given player.
        aliases: [fset]
        usage: /<command> [type] [player] <number>
    fc_bind:
        description: Binds a Force Power the given key.
        aliases: [fbind]
        usage: /<command> [key] [power] - key maybe a number or the name definde by Spout!

permissions:
    force.*:
        description: Grants access to all ForceCraft commands and powers.
        default: op
        children:
            force.admin: true
            force.user.*: true
    force.user.dark:
        description: Grants access to all Darkside Forces.
        default: false
        children:
            force.pull: true
            force.push: true
            force.choke: true
            force.bind: true
    force.user.light:
        description: Grants access to all Lightside Forces.
        default: false
        children:
            force.flash: true
            force.bind: true
    force.user.*:
        description: Grants access to all Forces.
        default: false
        children:
            force.user.dark: true
            force.user.light: true
    force.admin:
        description: Grants access to all commands.
        default: false
        children:
            force.info: true
            force.set: true
    force.info:
        description: Allows usage of the /finfo command.
        default: false
    force.set:
        description: Allows usage of the /fset command
        default: false
    force.pull:
        description: Allows usage of the Pull force.
        default: false
    force.choke:
        description: Allows usage of the Push force.
        default: false
    force.push:
        description: Allows usage of the Choke force.
        default: false
    force.bind:
        description: Allows usage of the /fbind command.
        default: false