name: TheLivingForce
main: de.Lathanael.TheLivingForce.bukkit.ForcePlugin
version: ${project.version} (BUILD ${git.build.time})
author: Lathanael
softdepend: [Spout]
description: >
             A plugin to implement the "Force" in Minecraft!

commands:
    force:
        description: Basic plugin Info
        default: true
        usage: /<command>