name: TheLivingForce
main: de.Lathanael.TheLivingForce.bukkit.ForcePlugin
version: ${project.version} (BUILD ${git.build.time})
author: Lathanael
depend: [Spout]
description: >
             A plugin to implement the "Force" in Minecraft!

commands:
    tlf_force:
        description: Basic plugin Info
        aliases: [force]
        usage: /<command>
    tlf_info:
        description: Gives info about the wanted player.
        aliases: [finfo]
        usage: /<command> [player]

permissions:
    force.user:
        description: Grants access to all user related commands.
        default: true
        children:
            force.pull: true
            force.push: true
            force.choke: true
    force.admin:
        description: Grants access to all commands.
        default: op
        children:
            force.info: true
    force.info:
        description: Allows usage of the /info command.
        default: false
    force.pull:
        description: Allows usage of the Pull force.
        default: false
    force.choke:
        description: Allows usage of the Push force.
        default: false
    force.push:
        description: Allows usage of the Choke force.
        default: false